//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahikariTaiV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class familia
    {
        public int id_familia { get; set; }
        public string name_lastname_parent { get; set; }
        public int id_grado { get; set; }
        public string phone_number { get; set; }
        public string rut_user { get; set; }
        public string gender { get; set; }
        public string live_with_him { get; set; }
    
        public virtual omitama omitama { get; set; }
        public virtual miembro miembro { get; set; }
    }
}
