//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahikariTaiV2.SR_DB {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_DB.DataBase_WSSoap")]
    public interface DataBase_WSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllMembers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AllMembers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllMembers", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> AllMembersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AllInfo(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> AllInfoAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AñadirMiembro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AñadirMiembro(
                    string rut, 
                    string nombres, 
                    string primerApellido, 
                    string segundoApellido, 
                    string genero, 
                    string categoria, 
                    string email, 
                    string birthdate, 
                    string nacionalidad, 
                    string phone, 
                    string calle, 
                    int numero, 
                    string region, 
                    string provincia, 
                    string comuna, 
                    string hobbies);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AñadirMiembro", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> AñadirMiembroAsync(
                    string rut, 
                    string nombres, 
                    string primerApellido, 
                    string segundoApellido, 
                    string genero, 
                    string categoria, 
                    string email, 
                    string birthdate, 
                    string nacionalidad, 
                    string phone, 
                    string calle, 
                    int numero, 
                    string region, 
                    string provincia, 
                    string comuna, 
                    string hobbies);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AñadirKenshu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AñadirKenshu(string rut, string dateIni, string dateInt, string dateSup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AñadirKenshu", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> AñadirKenshuAsync(string rut, string dateIni, string dateInt, string dateSup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarMiembro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ModificarMiembro(
                    string rut, 
                    string nombres, 
                    string primerApellido, 
                    string segundoApellido, 
                    string genero, 
                    string categoria, 
                    string email, 
                    string birthdate, 
                    string nacionalidad, 
                    string phone, 
                    string calle, 
                    int numero, 
                    string region, 
                    string provincia, 
                    string comuna, 
                    string hobbies);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarMiembro", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ModificarMiembroAsync(
                    string rut, 
                    string nombres, 
                    string primerApellido, 
                    string segundoApellido, 
                    string genero, 
                    string categoria, 
                    string email, 
                    string birthdate, 
                    string nacionalidad, 
                    string phone, 
                    string calle, 
                    int numero, 
                    string region, 
                    string provincia, 
                    string comuna, 
                    string hobbies);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarMiembro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EliminarMiembro(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarMiembro", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> EliminarMiembroAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Nacionalidades", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Nacionalidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Nacionalidades", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> NacionalidadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Generos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Generos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Generos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GenerosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Categorias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Categorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Categorias", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CategoriasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataBase_WSSoapChannel : MahikariTaiV2.SR_DB.DataBase_WSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataBase_WSSoapClient : System.ServiceModel.ClientBase<MahikariTaiV2.SR_DB.DataBase_WSSoap>, MahikariTaiV2.SR_DB.DataBase_WSSoap {
        
        public DataBase_WSSoapClient() {
        }
        
        public DataBase_WSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataBase_WSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataBase_WSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataBase_WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet AllMembers() {
            return base.Channel.AllMembers();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AllMembersAsync() {
            return base.Channel.AllMembersAsync();
        }
        
        public System.Data.DataSet AllInfo(string rut) {
            return base.Channel.AllInfo(rut);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AllInfoAsync(string rut) {
            return base.Channel.AllInfoAsync(rut);
        }
        
        public System.Data.DataSet AñadirMiembro(
                    string rut, 
                    string nombres, 
                    string primerApellido, 
                    string segundoApellido, 
                    string genero, 
                    string categoria, 
                    string email, 
                    string birthdate, 
                    string nacionalidad, 
                    string phone, 
                    string calle, 
                    int numero, 
                    string region, 
                    string provincia, 
                    string comuna, 
                    string hobbies) {
            return base.Channel.AñadirMiembro(rut, nombres, primerApellido, segundoApellido, genero, categoria, email, birthdate, nacionalidad, phone, calle, numero, region, provincia, comuna, hobbies);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AñadirMiembroAsync(
                    string rut, 
                    string nombres, 
                    string primerApellido, 
                    string segundoApellido, 
                    string genero, 
                    string categoria, 
                    string email, 
                    string birthdate, 
                    string nacionalidad, 
                    string phone, 
                    string calle, 
                    int numero, 
                    string region, 
                    string provincia, 
                    string comuna, 
                    string hobbies) {
            return base.Channel.AñadirMiembroAsync(rut, nombres, primerApellido, segundoApellido, genero, categoria, email, birthdate, nacionalidad, phone, calle, numero, region, provincia, comuna, hobbies);
        }
        
        public System.Data.DataSet AñadirKenshu(string rut, string dateIni, string dateInt, string dateSup) {
            return base.Channel.AñadirKenshu(rut, dateIni, dateInt, dateSup);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AñadirKenshuAsync(string rut, string dateIni, string dateInt, string dateSup) {
            return base.Channel.AñadirKenshuAsync(rut, dateIni, dateInt, dateSup);
        }
        
        public System.Data.DataSet ModificarMiembro(
                    string rut, 
                    string nombres, 
                    string primerApellido, 
                    string segundoApellido, 
                    string genero, 
                    string categoria, 
                    string email, 
                    string birthdate, 
                    string nacionalidad, 
                    string phone, 
                    string calle, 
                    int numero, 
                    string region, 
                    string provincia, 
                    string comuna, 
                    string hobbies) {
            return base.Channel.ModificarMiembro(rut, nombres, primerApellido, segundoApellido, genero, categoria, email, birthdate, nacionalidad, phone, calle, numero, region, provincia, comuna, hobbies);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ModificarMiembroAsync(
                    string rut, 
                    string nombres, 
                    string primerApellido, 
                    string segundoApellido, 
                    string genero, 
                    string categoria, 
                    string email, 
                    string birthdate, 
                    string nacionalidad, 
                    string phone, 
                    string calle, 
                    int numero, 
                    string region, 
                    string provincia, 
                    string comuna, 
                    string hobbies) {
            return base.Channel.ModificarMiembroAsync(rut, nombres, primerApellido, segundoApellido, genero, categoria, email, birthdate, nacionalidad, phone, calle, numero, region, provincia, comuna, hobbies);
        }
        
        public System.Data.DataSet EliminarMiembro(string rut) {
            return base.Channel.EliminarMiembro(rut);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> EliminarMiembroAsync(string rut) {
            return base.Channel.EliminarMiembroAsync(rut);
        }
        
        public System.Data.DataSet Nacionalidades() {
            return base.Channel.Nacionalidades();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> NacionalidadesAsync() {
            return base.Channel.NacionalidadesAsync();
        }
        
        public System.Data.DataSet Generos() {
            return base.Channel.Generos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GenerosAsync() {
            return base.Channel.GenerosAsync();
        }
        
        public System.Data.DataSet Categorias() {
            return base.Channel.Categorias();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CategoriasAsync() {
            return base.Channel.CategoriasAsync();
        }
    }
}
