//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahikariTaiV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudios
    {
        public int id_estudios { get; set; }
        public int id_grado_estudios { get; set; }
        public int career_years { get; set; }
        public string career_name { get; set; }
        public string name_center { get; set; }
        public string rut_user { get; set; }
    
        public virtual grado_estudios grado_estudios { get; set; }
        public virtual miembro miembro { get; set; }
    }
}
