//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahikariTaiV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public int id_job { get; set; }
        public string profession { get; set; }
        public string occupation { get; set; }
        public string rut_user { get; set; }
    
        public virtual miembro miembro { get; set; }
    }
}
