//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahikariTaiV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class miembro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public miembro()
        {
            this.admision = new HashSet<admision>();
            this.cargo = new HashSet<cargo>();
            this.estudios = new HashSet<estudios>();
            this.familia = new HashSet<familia>();
            this.job = new HashSet<job>();
            this.omitama_date = new HashSet<omitama_date>();
        }
    
        public int id_categoria { get; set; }
        public string nombres { get; set; }
        public string first_lastname { get; set; }
        public string second_lastname { get; set; }
        public int id_gender { get; set; }
        public string rut_user { get; set; }
        public System.DateTime birthdate { get; set; }
        public int id_nac { get; set; }
        public int id_direccion { get; set; }
        public string phone_number { get; set; }
        public string email { get; set; }
        public string hobbies { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admision> admision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cargo> cargo { get; set; }
        public virtual categoria categoria { get; set; }
        public virtual direccion direccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estudios> estudios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<familia> familia { get; set; }
        public virtual gender gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job> job { get; set; }
        public virtual nacionality nacionality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<omitama_date> omitama_date { get; set; }
    }
}
