//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahikariTaiV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class omitama_date
    {
        public int id_grado_date { get; set; }
<<<<<<< HEAD
        public int id_grado { get; set; }
=======
>>>>>>> 0ab54681af5a832b4fa47c249c04453d053ef103
        public System.DateTime grado_date { get; set; }
        public string rut_user { get; set; }
        public int id_grado { get; set; }
    
        public virtual miembro miembro { get; set; }
        public virtual omitama omitama { get; set; }
    }
}
